export const levelDevelopmentMap = {
  "Developed Countries": new Set(['US', 'JP', 'DE', 'GB', 'FR', 'IT', 'CA', 'KR', 'AT', 'AU', 'ES', 'NL', 'CH', 'TW', 'SE', 'BE', 'IE', 'IL', 'NO', 'DK', 'HK', 'SG', 'FI', 'CZ', 'PT', 'NZ', 'GR', 'SK', 'PR', 'LU', 'LT', 'SI', 'LV', 'EE', 'MO', 'CY', 'IS', 'MT', 'LI', 'SM']),
  "Emerging Market Countries": new Set(['DZ', 'AO', 'AR', 'BY', 'BR', 'BG', 'CL', 'CN', 'CO', 'HR', 'DO', 'EC', 'EG', 'HU', 'IN', 'ID', 'IR', 'KZ', 'KW', 'LB', 'MY', 'MX', 'MA', 'OM', 'PK', 'PE', 'PH', 'PL', 'QA', 'RO', 'RU', 'SA', 'ZA', 'LK', 'TH', 'TR', 'UA', 'AE', 'UY', 'VE', 'AM', 'AZ', 'BH', 'BN', 'IQ', 'MV', 'SY', 'TM', 'CV', 'GQ', 'SZ', 'GA', 'LY', 'SC', 'TN', 'AG', 'AW', 'BB', 'BZ', 'BO', 'CR', 'DM', 'SV', 'GD', 'GY', 'JM', 'PY', 'KN', 'LC', 'VC', 'SR', 'TT', 'AL', 'GT', 'XK', 'PA', 'GE', 'MK', 'BA', 'MN', 'JO', 'ME', 'RS', 'MU', 'BS', 'CU']),
  "Developing Countries": new Set(['AF', 'BD', 'BJ', 'BF', 'KH', 'CM', 'TD', 'CD', 'CG', 'CI', 'ET', 'GH', 'GN', 'HT', 'HN', 'KE', 'KG', 'LA', 'MG', 'MW', 'ML', 'MD', 'MZ', 'MM', 'NP', 'NI', 'NE', 'NG', 'PG', 'RW', 'SN', 'SD', 'TJ', 'TZ', 'UG', 'UZ', 'VN', 'YE', 'ZM', 'ZW', 'BT', 'TL', 'BI', 'CF', 'KM', 'ER', 'GM', 'GW', 'LS', 'LR', 'MR', 'ST', 'SL', 'SO', 'SS', 'TG', 'EH', 'DJ', 'BW', 'KP', 'PS']),
}

export const byRegionMap = {
  'Asia': new Set(['AF', 'AM', 'AZ', 'BH', 'BD', 'BT', 'BN', 'KH', 'CN', 'CY', 'GE', 'HK', 'IN', 'ID', 'IR', 'IQ', 'IL', 'JP', 'JO', 'KZ', 'KP', 'KR', 'KW', 'KG', 'LA', 'LB', 'MO', 'MY', 'MV', 'MN', 'MM', 'NP', 'OM', 'PK', 'PS', 'PH', 'QA', 'SA', 'SG', 'LK', 'SY', 'TW', 'TJ', 'TH', 'TL', 'TR', 'TM', 'AE', 'UZ', 'VN', 'YE']),
  'Africa': new Set(['DZ', 'AO', 'BJ', 'BW', 'IO', 'BF', 'BI', 'CV', 'CM', 'CF', 'TD', 'KM', 'CG', 'CD', 'CI', 'DJ', 'EG', 'GQ', 'ER', 'SZ', 'ET', 'TF', 'GA', 'GM', 'GH', 'GN', 'GW', 'KE', 'LS', 'LR', 'LY', 'MG', 'MW', 'ML', 'MR', 'MU', 'YT', 'MA', 'MZ', 'NE', 'NG', 'RE', 'RW', 'SH', 'ST', 'SN', 'SC', 'SL', 'SO', 'ZA', 'SS', 'SD', 'TZ', 'TG', 'TN', 'UG', 'EH', 'ZM', 'ZW']),
  'North America': new Set(['BM', 'CA', 'GL', 'PM', 'US']),
  'Latin America & the Carribean': new Set(['AI', 'AG', 'AR', 'AW', 'BS', 'BB', 'BZ', 'BO', 'BQ', 'BV', 'BR', 'KY', 'CL', 'CO', 'CR', 'CU', 'CW', 'DM', 'DO', 'EC', 'SV', 'FK', 'GF', 'GD', 'GP', 'GT', 'GY', 'HT', 'HN', 'JM', 'MQ', 'MX', 'MS', 'NI', 'PA', 'PY', 'PE', 'PR', 'BL', 'KN', 'LC', 'MF', 'VC', 'SX', 'GS', 'SR', 'TT', 'TC', 'UY', 'VE', 'VG', 'VI']),
  'Europe': new Set(['AX', 'AL', 'AD', 'AT', 'BY', 'BE', 'BA', 'BG', 'HR', 'CZ', 'DK', 'EE', 'FO', 'FI', 'FR', 'DE', 'GI', 'GR', 'GG', 'VA', 'HU', 'IS', 'IE', 'IM', 'IT', 'JE', 'LV', 'LI', 'LT', 'LU', 'MT', 'MD', 'MC', 'ME', 'NL', 'MK', 'NO', 'PL', 'PT', 'RO', 'RU', 'SM', 'RS', 'SK', 'SI', 'ES', 'SJ', 'SE', 'CH', 'UA', 'GB']),
  'Australia & New Zealand': new Set(['AU', 'CX', 'CC', 'HM', 'NZ', 'NF'])
}
